function d(a){throw a;}var f=void 0;function j(a,e,b){e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b>=a.length&&d(Error("Trying to read beyond buffer length"));return a[b]}function l(a,e,b){var c=0;e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+1>=a.length&&d(Error("Trying to read beyond buffer length"));"big"==e?(c=a[b]<<8,c|=a[b+1]):(c=a[b],c|=a[b+1]<<8);return c}
function m(a,e,b){var c=0;e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+3>=a.length&&d(Error("Trying to read beyond buffer length"));"big"==e?(c=a[b+1]<<16,c|=a[b+2]<<8,c|=a[b+3],c=16777216*a[b]+c):(c=a[b+2]<<16,c|=a[b+1]<<8,c|=a[b],c=16777216*a[b+3]+c);return c}
function n(a,e,b){var c=Array(2);e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+7>=a.length&&d(Error("Trying to read beyond buffer length"));"big"==e?(c[0]=m(a,e,b),c[1]=m(a,e,b+4)):(c[0]=m(a,e,b+4),c[1]=m(a,e,b));return c}function o(a,e,b){e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b>=a.length&&d(Error("Trying to read beyond buffer length"));return!(a[b]&128)?a[b]:-1*(255-a[b]+1)}
function p(a,e,b){e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+1>=a.length&&d(Error("Trying to read beyond buffer length"));a=l(a,e,b);return!(a&32768)?a:-1*(65535-a+1)}function q(a,e,b){e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+3>=a.length&&d(Error("Trying to read beyond buffer length"));a=m(a,e,b);return!(a&2147483648)?a:-1*(4294967295-a+1)}
function r(a,e,b){e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+3>=a.length&&d(Error("Trying to read beyond buffer length"));a=n(a,e,b);if(!(a[0]&2147483648))return a;a[0]=-1*(4294967295-a[0]);a[1]=-1*(4294967295-a[1]+1);return a}
function s(a,e,b){var c=[];e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+3>=a.length&&d(Error("Trying to read beyond buffer length"));"big"==e?(c[0]=a[b],c[1]=a[b+1],c[2]=a[b+2],c[3]=a[b+3]):(c[3]=a[b],c[2]=a[b+1],c[1]=a[b+2],c[0]=a[b+3]);a=c[0]&128;e=(c[0]&127)<<1;e|=(c[1]&128)>>>7;b=(c[1]&127)<<16;b|=c[2]<<8;b|=c[3];if(!a&&255==e&&0===b)return Number.POSITIVE_INFINITY;if(a&&255==e&&0===b)return Number.NEGATIVE_INFINITY;if(255==e&&0!==b)return Number.NaN;
if(0===e&&0===b)return 0;e-=127;-127==e?(e++,c=0):c=1;c=(c+b*Math.pow(2,-23))*Math.pow(2,e);a&&(c*=-1);return c}
function t(a,e,b){var c=[],h;e===f&&d(Error("missing endian"));a===f&&d(Error("missing buffer"));b===f&&d(Error("missing offset"));b+7>=a.length&&d(Error("Trying to read beyond buffer length"));"big"==e?(c[0]=a[b],c[1]=a[b+1],c[2]=a[b+2],c[3]=a[b+3],c[4]=a[b+4],c[5]=a[b+5],c[6]=a[b+6],c[7]=a[b+7]):(c[7]=a[b],c[6]=a[b+1],c[5]=a[b+2],c[4]=a[b+3],c[3]=a[b+4],c[2]=a[b+5],c[1]=a[b+6],c[0]=a[b+7]);a=c[0]&128;e=(c[0]&127)<<4;e|=(c[1]&240)>>>4;h=c[7];h|=c[6]<<8;h|=c[5]<<16;b=c[4];b|=c[3]<<8;b|=c[2]<<16;b|=
(c[1]&15)<<24;b*=Math.pow(2,24);b+=h;if(!a&&2047==e&&0===b)return Number.POSITIVE_INFINITY;if(a&&2047==e&&0===b)return Number.NEGATIVE_INFINITY;if(2047==e&&0!==b)return Number.NaN;if(0===e&&0===b)return 0;e-=1023;-1023==e?(e++,c=0):c=1;c=(c+b*Math.pow(2,-52))*Math.pow(2,e);a&&(c*=-1);return c}
function u(a,e){"number"!=typeof a&&d(new (Error("cannot write a non-number as a number")));0>a&&d(Error("specified a negative value for writing an unsigned value"));a>e&&d(Error("value is larger than maximum value for type"));Math.floor(a)!==a&&d(Error("value has a fractional component"));return a}
function v(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=u(a,255);b[c]=a}
function w(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+1>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=u(a,65535);"big"==e?(b[c]=(a&65280)>>>8,b[c+1]=a&255):(b[c+1]=(a&65280)>>>8,b[c]=a&255)}
function x(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+3>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=u(a,4294967295);"big"==e?(b[c]=(a-(a&16777215))/Math.pow(2,24),b[c+1]=a>>>16&255,b[c+2]=a>>>8&255,b[c+3]=a&255):(b[c+3]=(a-(a&16777215))/Math.pow(2,24),b[c+2]=a>>>16&255,b[c+1]=a>>>8&255,b[c]=a&255)}
function y(a,e,b,c){a===f&&d(Error("missing value"));a instanceof Array||d(Error("value must be an array"));2!=a.length&&d(Error("value must be an array of length 2"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+7>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));u(a[0],4294967295);u(a[1],4294967295);"big"==e?(x(a[0],e,b,c),x(a[1],e,b,c+3)):(x(a[0],e,b,c+3),x(a[1],e,b,c))}
function z(a,e,b){"number"!=typeof a&&d(new (Error("cannot write a non-number as a number")));a>e&&d(Error("value larger than maximum allowed value"));a<b&&d(Error("value smaller than minimum allowed value"));Math.floor(a)!==a&&d(Error("value has a fractional component"));return a}
function A(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=z(a,127,-240);0<=a?v(a,e,b,c):v(255+a+1,e,b,c)}
function B(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+1>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=z(a,32767,-61440);0<=a?w(a,e,b,c):w(65535+a+1,e,b,c)}
function C(a,e,b,c){a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+3>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));a=z(a,2147483647,-4026531840);0<=a?x(a,e,b,c):x(4294967295+a+1,e,b,c)}
function D(a,e,b,c){var h=Array(2);a===f&&d(Error("missing value"));a instanceof Array||d(Error("value must be an array"));2!=a.length&&d(Error("value must be an array of length 2"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+7>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));z(a[0],2147483647,-4026531840);z(a[1],4294967295,-4294967295);0>a[0]||0>a[1]?(h[0]=4294967295-Math.abs(a[0]),h[1]=4294967296-Math.abs(a[1]),
4294967296==h[1]&&(h[1]=0,h[0]++)):(h[0]=a[0],h[1]=a[1]);"big"==e?(x(h[0],e,b,c),x(h[1],e,b,c+4)):(x(h[0],e,b,c+4),x(h[1],e,b,c))}
function E(a,e,b,c){var h,i,k,g=[];a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+3>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));isNaN(a)?(h=0,i=255,a=23):a==Number.POSITIVE_INFINITY?(h=0,i=255,a=0):a==Number.NEGATIVE_INFINITY?(h=1,i=255,a=0):(0>a?(h=1,a=Math.abs(a)):h=0,k=Math.floor(Math.log(a)/Math.log(2)),-127>=k)?(i=0,a=a*Math.pow(2,149)&8388607):(i=127+k,a*=Math.pow(2,
23-k),a&=8388607);g[0]=h<<7|(i&254)>>>1;g[1]=(i&1)<<7|(a&8323072)>>>16;g[2]=(a&65280)>>>8;g[3]=a&255;"big"==e?(b[c]=g[0],b[c+1]=g[1],b[c+2]=g[2],b[c+3]=g[3]):(b[c]=g[3],b[c+1]=g[2],b[c+2]=g[1],b[c+3]=g[0])}
function F(a,e,b,c){var h,i,k,g=[];a===f&&d(Error("missing value"));e===f&&d(Error("missing endian"));b===f&&d(Error("missing buffer"));c===f&&d(Error("missing offset"));c+7>=b.length&&b instanceof Buffer&&d(Error("Trying to write beyond buffer length"));isNaN(a)?(h=0,i=2047,a=23):a==Number.POSITIVE_INFINITY?(h=0,i=2047,a=0):a==Number.NEGATIVE_INFINITY?(h=1,i=2047,a=0):(0>a?(h=1,a=Math.abs(a)):h=0,k=Math.floor(Math.log(a)/Math.log(2)),2.225073858507201E-308>=a||-1023>=k?(i=0,a=a*Math.pow(2,1023)*
Math.pow(2,51)):(1023<k&&(k=1023),i=1023+k,a*=Math.pow(2,-k),a*=Math.pow(2,52)),a%=Math.pow(2,52));g[7]=a&255;g[6]=a>>>8&255;g[5]=a>>>16&255;a=(a-(a&16777215))/Math.pow(2,24);g[4]=a&255;g[3]=a>>>8&255;g[2]=a>>>16&255;g[1]=(i&15)<<4|a>>>24;g[0]=h<<7|(i&2032)>>>4;"big"==e?(b[c]=g[0],b[c+1]=g[1],b[c+2]=g[2],b[c+3]=g[3],b[c+4]=g[4],b[c+5]=g[5],b[c+6]=g[6],b[c+7]=g[7]):(b[c+7]=g[0],b[c+6]=g[1],b[c+5]=g[2],b[c+4]=g[3],b[c+3]=g[4],b[c+2]=g[5],b[c+1]=g[6],b[c]=g[7])}exports.j=j;exports.g=l;exports.h=m;
exports.i=n;exports.t=v;exports.q=w;exports.r=x;exports.s=y;exports.f=o;exports.c=p;exports.d=q;exports.e=r;exports.p=A;exports.m=B;exports.n=C;exports.o=D;exports.b=s;exports.a=t;exports.l=E;exports.k=F;exports.ruint8=j;exports.ruint16=l;exports.ruint32=m;exports.ruint64=n;exports.wuint8=v;exports.wuint16=w;exports.wuint32=x;exports.wuint64=y;exports.rsint8=o;exports.rsint16=p;exports.rsint32=q;exports.rsint64=r;exports.wsint8=A;exports.wsint16=B;exports.wsint32=C;exports.wsint64=D;
exports.rfloat=s;exports.rdouble=t;exports.wfloat=E;exports.wdouble=F;
